Support dynamic import
dynamic import support has just landed in [Rollup 0.55.0](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#upcoming-0550).
When testing a project that uses buble via rollup-plugin-buble, I
noticed that it doesn't support dynamic import yet, resulting in the
error

```
SyntaxError: Unexpected token in ...
```

Looking at the [rollup source code](https://github.com/rollup/rollup/blob/089c9e06190b894d766fc44571752fa91dc1eaa5/src/Graph.ts#L3), I see that they are using [acorn-dynamic-import](https://github.com/kesne/acorn-dynamic-import).
This pull request therefore adds the acorn-dynamic-import plugin as done in rollup
itself so that buble is able to parse code that uses dynamic import.

I've also created a small test file that fails without these changes.
Let me know if it's enought or if I should write more tests.